dist: xenial
sudo: required
language: python
python:
  - "3.7"


addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - g++-8
     - libhdf5-dev
     - hdf5-tools

env:
 - CXX=g++-8 && PYTHONPATH=$PYTHONPATH:$(pwd)/build/stage/lib/cppe

before_script:
  - pip install pytest numpy
  - pip install h5py
  - pip install numba
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=on -DCMAKE_CXX_COMPILER=$CXX -DENABLE_PYTHON_INTERFACE=ON ..

script:
  - cmake --version
  - make
  - cd ..
  - pytest
