sudo: required
language: python
dist: xenial

compiler:
  - gcc

addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - g++-8
     - gcc-8
     - gfortran-8
     - libhdf5-dev
     - hdf5-tools
     - python3

env:
 - CXX=g++-8 && PYTHONPATH=$PYTHONPATH:$(pwd)/build/stage/lib

before_script:
  - sudo pip install pytest numpy
  - sudo pip install h5py
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=on -DCMAKE_CXX_COMPILER=$CXX -DENABLE_PYTHON_INTERFACE=ON ..

script:
  - cmake --version
  - make
  - cd ..
  - pytest
