sudo: required
language: cpp
dist: trusty

compiler:
  - gcc

addons:
 apt:
   sources:
     - ubuntu-toolchain-r-test
   packages:
     - g++-8
     - gcc-8
     - gfortran-8
     - python3-pip

env:
 - CC=gcc-8 && CXX=g++-8 && FC=gfortran-8 && PYTHONPATH=$PYTHONPATH:$(pwd)/build/stage/lib

before_script:
  - sudo pip3 install pytest numpy
  - sudo pip3 install pyscf
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=on -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC -DCMAKE_Fortran_COMPILER=$FC ..

script:
  - cmake --version
  - make
  - cd ..
  - pytest
