sudo: required
language: cpp
dist: trusty

compiler:
  - gcc

- os: linux
       addons:
         apt:
           sources:
             - ubuntu-toolchain-r-test
           packages:
             - g++-8
       env:
         - CC=gcc-8
         - CXX=g++-8

before_script:
  - mkdir build
  - cd build
  - cmake -DBUILD_SHARED_LIBS=on -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_C_COMPILER=$CC ..

script:
  - cmake --version
  - make
